### ISSUE TITLE
Tilrettelægge opgaverne mht spil-logik

### ISSUE THREAD

**Issue by laererlund** [Slotshaven-programmering2019/Matador2019#5]

**Comment by zxstai** [comment]
Fængsel (nem) bliver lavet af @Bm2mhc (Marinus)
Handel (svær) bliver lavet af @saratims123 (sara) @zxstai (M. Hansen) @miajensen  (Mia) @NatasjaDamsbjerg (Natasja) @KKP1703 (Kristoffer)
chancekort (semi svær) bliver lavet af @nissemand243 (Alexander)
